trigger: none

# Uncomment to enable manual trigger with parameters
# parameters:
#   - name: maxConcurrent
#     displayName: 'Maximum Concurrent Migrations'
#     type: number
#     default: 3
#     values:
#       - 1
#       - 2
#       - 3
#       - 4
#       - 5

variables:
  - group: core-entauto-github-migration-secrets
  - name: maxConcurrent
    value: 3  # Adjust based on your needs (1-5)

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: PrerequisiteValidation
    displayName: 'prereq Validation'
    jobs:
      - job: ValidatePrerequisites
        displayName: 'Check Prerequisites'
        steps:
          - checkout: self
          
          - task: Bash@3
            displayName: 'Validate repos.csv File'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "=========================================="
                echo "PREREQUISITE VALIDATION"
                echo "=========================================="
                
                # Check if repos.csv exists
                CSV_FILE="bash/repos.csv"
                if [ ! -f "$CSV_FILE" ]; then
                  echo "❌ ERROR: repos.csv file not found at $CSV_FILE"
                  exit 1
                fi
                echo "✅ repos.csv file exists"
                
                # Check if file is not empty
                if [ ! -s "$CSV_FILE" ]; then
                  echo "❌ ERROR: repos.csv file is empty"
                  exit 1
                fi
                echo "✅ repos.csv file is not empty"
                
                # Read header and validate required columns
                HEADER=$(head -n 1 "$CSV_FILE")
                echo ""
                echo "CSV Header: $HEADER"
                echo ""
                
                # Check for required columns
                REQUIRED_COLUMNS=("github_org" "github_repo" "gh_repo_visibility")
                MISSING_COLUMNS=()
                
                for col in "${REQUIRED_COLUMNS[@]}"; do
                  if ! echo "$HEADER" | grep -q "$col"; then
                    MISSING_COLUMNS+=("$col")
                  fi
                done
                
                if [ ${#MISSING_COLUMNS[@]} -gt 0 ]; then
                  echo "❌ ERROR: Missing required columns in repos.csv:"
                  for col in "${MISSING_COLUMNS[@]}"; do
                    echo "  - $col"
                  done
                  exit 1
                fi
                
                echo "✅ All required columns present: ${REQUIRED_COLUMNS[*]}"
                
                # Count repositories to migrate
                REPO_COUNT=$(($(wc -l < "$CSV_FILE") - 1))
                echo ""
                echo "✅ Found $REPO_COUNT repositories to process"
                echo "=========================================="

  - stage: MigrationReadinessCheck
    displayName: 'active pr & pipeline check'
    dependsOn: PrerequisiteValidation
    jobs:
      - job: ReadinessCheck
        displayName: 'Run Readiness Check Script'
        steps:
          - checkout: self
          
          - task: Bash@3
            displayName: 'Install GitHub CLI'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "Installing GitHub CLI..."
                type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh -y
                
                echo ""
                echo "✅ GitHub CLI installed:"
                gh --version

          - task: Bash@3
            displayName: 'Execute Migration Readiness Check'
            inputs:
              targetType: 'filePath'
              filePath: 'bash/1_migration_readiness_check.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
            env:
              GH_TOKEN: $(GH_TOKEN)
              GH_PAT: $(GH_TOKEN)
              ADO_PAT: $(ADO_PAT)
      
      - job: WaitForApprovalToMigrate
        displayName: '⏸️ Approve to START MIGRATION'
        dependsOn: ReadinessCheck
        condition: succeeded()
        pool: server
        timeoutInMinutes: 1440
        steps:
          - task: ManualValidation@0
            displayName: 'Review Readiness & Approve Migration'
            inputs:
              notifyUsers: '$(Build.RequestedForEmail)'
              instructions: |
                ## 📋 Active PR & Pipeline Check COMPLETED
                
                ⚠️ **IMPORTANT**: The next stage will migrate repositories to GitHub.
                
                ### 📊 What to Review
                1. Check the readiness check logs above
                2. Verify all repositories are accessible
                3. Confirm GitHub organizations exist
                4. Ensure permissions are validated
                
                ### ⏭️ Next Stage: Repo Migration
                This will:
                - Migrate repositories to GitHub
                - Transfer Git history
                - Create GitHub repositories
                
                ---
                
                ✅ Click **Resume** to START MIGRATION
                ❌ Click **Reject** to stop the pipeline
              onTimeout: 'reject'

  - stage: Migration
    displayName: 'repo migration'
    dependsOn: MigrationReadinessCheck
    jobs:
      - job: RunMigration
        displayName: 'Run Migration Script'
        steps:
          - checkout: self
          
          - task: Bash@3
            displayName: 'Install GitHub CLI'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "Installing GitHub CLI..."
                type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh -y
                
                echo ""
                echo "✅ GitHub CLI installed:"
                gh --version

          - task: Bash@3
            displayName: 'Install gh-ado2gh Extension'
            inputs:
              targetType: 'inline'
              script: |
                echo "Installing gh-ado2gh extension..."
                gh extension install github/gh-ado2gh
                
                echo ""
                echo "✅ Extension installed:"
                gh extension list
            env:
              GH_TOKEN: $(GH_TOKEN)

          - task: Bash@3
            displayName: 'Execute Migration'
            inputs:
              targetType: 'filePath'
              filePath: 'bash/2_migration.sh'
              arguments: '--csv bash/repos.csv --max-concurrent $(maxConcurrent)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
            env:
              GH_TOKEN: $(GH_TOKEN)
              GH_PAT: $(GH_TOKEN)
              ADO_PAT: $(ADO_PAT)
            timeoutInMinutes: 120  # 2 hours timeout for large migrations

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Migration Logs'
            condition: always()
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: 'migration-logs'
              publishLocation: 'Container'
            continueOnError: true

  - stage: PostMigrationValidation
    displayName: 'repo migration validation'
    dependsOn: Migration
    jobs:
      - job: ValidationCheck
        displayName: 'Run Validation Script'
        steps:
          - checkout: self
          
          - task: Bash@3
            displayName: 'Install GitHub CLI'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "Installing GitHub CLI..."
                type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh -y
                
                echo ""
                echo "✅ GitHub CLI installed:"
                gh --version

          - task: Bash@3
            displayName: 'Execute Post-Migration Validation'
            inputs:
              targetType: 'filePath'
              filePath: 'bash/3_post_migration_validation.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
            env:
              GH_TOKEN: $(GH_TOKEN)
              GH_PAT: $(GH_TOKEN)
              ADO_PAT: $(ADO_PAT)
            timeoutInMinutes: 60

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Validation Logs'
            condition: always()
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: 'validation-logs'
              publishLocation: 'Container'
            continueOnError: true

          - task: Bash@3
            displayName: 'Migration Summary'
            condition: always()
            inputs:
              targetType: 'inline'
              script: |
                echo "=========================================="
                echo "MIGRATION SUMMARY"
                echo "=========================================="
                echo "Pipeline: $(Build.DefinitionName)"
                echo "Build Number: $(Build.BuildNumber)"
                echo "Build ID: $(Build.BuildId)"
                echo ""
                echo "Artifacts published:"
                echo "  - migration-logs"
                echo "  - validation-logs"
                echo ""
                echo "Review artifacts for detailed migration results."
                echo "=========================================="
      
      - job: WaitForApprovalToRewire
        displayName: '⏸️ Approve to START PIPELINE REWIRING'
        dependsOn: ValidationCheck
        condition: succeeded()
        pool: server
        timeoutInMinutes: 1440
        steps:
          - task: ManualValidation@0
            displayName: 'Review Validation & Approve Rewiring'
            inputs:
              notifyUsers: '$(Build.RequestedForEmail)'
              instructions: |
                ## 📋 Repo Migration Validation COMPLETED
                
                ⚠️ **IMPORTANT**: The next stage will rewire pipelines to use GitHub repositories.
                
                ### 📊 What to Review
                1. Download and review the **migration-logs** artifact
                2. Download and review the **validation-logs** artifact
                3. Verify all repositories migrated successfully
                4. Check validation results for any issues
                5. Confirm commit history is intact
                
                ### ⏭️ Next Stage: Pipeline Rewiring
                This will:
                - Update ADO pipelines to point to GitHub repositories
                - Modify pipeline configurations
                - Change repository sources
                
                ### 📁 Artifacts to Review
                - migration-logs: Migration execution details
                - validation-logs: Validation check results
                
                ---
                
                ✅ Click **Resume** to START PIPELINE REWIRING
                ❌ Click **Reject** to stop before rewiring
              onTimeout: 'reject'

  - stage: PipelineRewiring
    displayName: 'pipeline rewiring'
    dependsOn: PostMigrationValidation
    condition: succeeded()
    jobs:
      - job: RewirePipelines
        displayName: 'Run Pipeline Rewiring'
        steps:
          - checkout: self
          
          - task: Bash@3
            displayName: 'Install GitHub CLI'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "Installing GitHub CLI..."
                type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                sudo apt update
                sudo apt install gh -y
                
                echo ""
                echo "✅ GitHub CLI installed:"
                gh --version

          - task: Bash@3
            displayName: 'Install gh-ado2gh Extension'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                echo "Installing gh-ado2gh extension..."
                gh extension install github/gh-ado2gh
                
                echo ""
                echo "✅ Extension installed:"
                gh extension list
            env:
              GH_TOKEN: $(GH_TOKEN)

          - task: Bash@3
            displayName: 'Make Rewire Script Executable'
            inputs:
              targetType: 'inline'
              script: |
                chmod +x bash/4_rewire_pipeline.sh
                echo "✅ Script permissions set"

          - task: Bash@3
            displayName: 'Execute Pipeline Rewiring'
            inputs:
              targetType: 'filePath'
              filePath: 'bash/4_rewire_pipeline.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
            env:
              GH_TOKEN: $(GH_TOKEN)
              GH_PAT: $(GH_TOKEN)
              ADO_PAT: $(ADO_PAT)
            timeoutInMinutes: 60

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Rewiring Logs'
            condition: always()
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: 'rewiring-logs'
              publishLocation: 'Container'
            continueOnError: true

          - task: Bash@3
            displayName: 'Rewiring Summary'
            condition: always()
            inputs:
              targetType: 'inline'
              script: |
                echo "=========================================="
                echo "PIPELINE REWIRING SUMMARY"
                echo "=========================================="
                echo "Build Number: $(Build.BuildNumber)"
                echo ""
                echo "Check the rewiring-logs artifact for detailed results"
                echo "Log files: pipeline-rewiring-*.txt"
                echo "=========================================="
