#!/usr/bin/env bash

################################################################################
# Reclaim Mannequins Script
# 
# This script reclaims mannequins (placeholder users) by mapping them to actual
# GitHub users based on the updated mannequin CSV files.
#
# Prerequisites:
#   - mannequins-*.csv files with updated 'target' column (in bash/ folder)
#   - GH_PAT environment variable (GitHub Personal Access Token)
#   - gh CLI installed with ado2gh extension
#
# Usage:
#   ./7b_reclaim_mannequins.sh
#
# Note: The mannequin CSV files should have been generated by 7a_generate_mannequins.sh
#       and manually edited to fill in the 'target' column with actual GitHub usernames.
################################################################################

set -euo pipefail

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Counters for summary
TOTAL_ORGS=0
SUCCESSFUL_RECLAIMS=0
FAILED_RECLAIMS=0

# Log file
LOG_FILE="reclaim-mannequins-$(date +%Y%m%d-%H%M%S).log"

################################################################################
# Logging Functions
################################################################################

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${YELLOW}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

log_section() {
    echo "" | tee -a "$LOG_FILE"
    echo "==========================================================================" | tee -a "$LOG_FILE"
    echo -e "${CYAN}$1${NC}" | tee -a "$LOG_FILE"
    echo "==========================================================================" | tee -a "$LOG_FILE"
}

################################################################################
# Validation Functions
################################################################################

validate_prerequisites() {
    log_section "VALIDATING PREREQUISITES"
    
    # Check for required environment variables
    if [ -z "${GH_PAT:-}" ]; then
        log_error "GH_PAT environment variable is not set"
        echo "##[error]GH_PAT environment variable is not set"
        exit 1
    fi
    log_success "GH_PAT is set"
    
    # Check if gh CLI is installed
    if ! command -v gh &> /dev/null; then
        log_error "gh CLI is not installed"
        exit 1
    fi
    log_success "gh CLI is installed: $(gh --version | head -n 1)"
    
    # Check if any mannequin CSV files exist
    if ! ls bash/mannequins-*.csv 1> /dev/null 2>&1; then
        log_error "No mannequin CSV files found in bash/ folder"
        log_error "Expected files: bash/mannequins-*.csv"
        log_error "Please ensure you have:"
        log_error "  1. Generated mannequin CSV files using 7a_generate_mannequins.sh"
        log_error "  2. Downloaded and edited the CSV files to fill in the 'target' column"
        log_error "  3. Committed the updated CSV files back to the repository"
        echo "##[error]No mannequin CSV files found"
        exit 1
    fi
    log_success "Mannequin CSV files found in bash/ folder"
}

################################################################################
# Reclaim Mannequins
################################################################################

reclaim_mannequins_for_org() {
    local csv_file="$1"
    local github_org
    
    # Extract github_org from filename: mannequins-{org}.csv
    github_org=$(basename "$csv_file" .csv | sed 's/^mannequins-//')
    
    log_info "Reclaiming mannequins for GitHub org: ${github_org}"
    log_info "Using CSV file: ${csv_file}"
    
    # Check if CSV has any mappings (more than just header)
    local line_count=$(wc -l < "$csv_file")
    if [ "$line_count" -le 1 ]; then
        log_warning "CSV file ${csv_file} has no mannequin mappings (only header), skipping"
        return 0
    fi
    
    # Set environment variables for gh CLI
    export GH_TOKEN="${GH_PAT}"
    
    # Execute gh ado2gh reclaim-mannequin command
    if gh ado2gh reclaim-mannequin \
        --github-org "${github_org}" \
        --csv "${csv_file}" \
        >> "$LOG_FILE" 2>&1; then
        
        log_success "Successfully reclaimed mannequins for ${github_org}"
        return 0
    else
        log_error "Failed to reclaim mannequins for ${github_org}"
        return 1
    fi
}

################################################################################
# Main Processing Logic
################################################################################

process_mannequin_csv_files() {
    log_section "RECLAIMING MANNEQUINS"
    
    # Find all mannequin CSV files
    local csv_files=(bash/mannequins-*.csv)
    TOTAL_ORGS=${#csv_files[@]}
    
    log_info "Found ${TOTAL_ORGS} mannequin CSV file(s) to process"
    echo "" | tee -a "$LOG_FILE"
    
    for csv_file in "${csv_files[@]}"; do
        local github_org
        github_org=$(basename "$csv_file" .csv | sed 's/^mannequins-//')
        
        log_section "GitHub Organization: ${github_org}"
        log_info "CSV File: ${csv_file}"
        
        if reclaim_mannequins_for_org "$csv_file"; then
            SUCCESSFUL_RECLAIMS=$((SUCCESSFUL_RECLAIMS + 1))
        else
            FAILED_RECLAIMS=$((FAILED_RECLAIMS + 1))
        fi
        
        echo "" | tee -a "$LOG_FILE"
    done
}

################################################################################
# Summary Report
################################################################################

print_summary() {
    log_section "MANNEQUIN RECLAMATION SUMMARY"
    
    echo "" | tee -a "$LOG_FILE"
    echo "Total GitHub Organizations:      ${TOTAL_ORGS}" | tee -a "$LOG_FILE"
    echo "Successfully Reclaimed:          ${SUCCESSFUL_RECLAIMS}" | tee -a "$LOG_FILE"
    echo "Failed to Reclaim:               ${FAILED_RECLAIMS}" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
    echo "Log file: ${LOG_FILE}" | tee -a "$LOG_FILE"
    echo "==========================================================================" | tee -a "$LOG_FILE"
    
    if [ $FAILED_RECLAIMS -gt 0 ]; then
        log_warning "Some mannequin reclamations failed. Please review the log file for details."
        echo "##[warning]Mannequin reclamation completed with $FAILED_RECLAIMS failures"
        echo "##vso[task.logissue type=warning]Reclaim mannequins: $SUCCESSFUL_RECLAIMS succeeded, $FAILED_RECLAIMS failed"
    elif [ $TOTAL_ORGS -eq 0 ]; then
        log_warning "No mannequin CSV files were processed."
        echo "##[warning]No mannequin CSV files were processed"
        echo "##vso[task.logissue type=warning]Reclaim mannequins: No CSV files found to process"
    else
        log_success "All mannequins reclaimed successfully!"
        echo "##vso[task.logissue type=warning]All $SUCCESSFUL_RECLAIMS organizations processed successfully"
    fi
    
    # Always exit 0 to allow pipeline to continue
    exit 0
}

################################################################################
# Main Execution
################################################################################

main() {
    log_section "RECLAIM MANNEQUINS"
    log_info "Script started at: $(date)"
    log_info "Log file: ${LOG_FILE}"
    
    validate_prerequisites
    process_mannequin_csv_files
    print_summary
    
    log_info "Script completed at: $(date)"
}

# Execute main function
main
